### ISSUE TITLE
 python3 sscollector.pyz -h | Error

### ISSUE THREAD

**Issue by mdaslamansari** [Azure/Stormspotter#20] opened 2020-09-07 09:56 UTC
I got below error while trying to run -  python3 sscollector.pyz -h

Note - I am using Ubuntu OS

File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/.shiv/sscollector_f1bc86a4f6f6fe47e7a3adca48b68f91357a3dc18de4c8a256722b4a00ef2273/site-packages/main.py", line 14, in <module>
    from stormcollector.aad import query_aad
  File "/root/.shiv/sscollector_f1bc86a4f6f6fe47e7a3adca48b68f91357a3dc18de4c8a256722b4a00ef2273/site-packages/stormcollector/aad.py", line 9, in <module>
    from .auth import Context
  File "/root/.shiv/sscollector_f1bc86a4f6f6fe47e7a3adca48b68f91357a3dc18de4c8a256722b4a00ef2273/site-packages/stormcollector/auth.py", line 43, in <module>
    class Context:
  File "/root/.shiv/sscollector_f1bc86a4f6f6fe47e7a3adca48b68f91357a3dc18de4c8a256722b4a00ef2273/site-packages/stormcollector/auth.py", line 68, in Context
    ) -> Tuple[identity.AzureCliCredential, identity_aio.AzureCliCredential]:
AttributeError: module 'azure.identity' has no attribute 'AzureCliCredential'

**Comment by legra-ms** [comment] 2020-09-08 01:36
I haven't been able to reproduce that error on any of my Linux distros or WSL.

It could be that you have some conflicting packages somewhere since AzureCliCredential was only introduced in Azure Identity 1.4.0.  Could you try clearing your `~/.shiv` folder and rerunning it?

**Comment by mdaslamansari** [comment] 2020-09-08 10:41
Running this command (python3 -c 'import azure.identity;print(azure.identity.__version__)') gave me result as "1.2.0". I installed 1.4.0 version and when running the above command, still getting the same result of 1.2.0. Not able to understand why the dist-packages are not getting upgraded with it.

![image](https://user-images.githubusercontent.com/3599811/92466571-edf4ad80-f1ed-11ea-8f75-21f66cb91653.png)

**Comment by mdaslamansari** [comment] 2020-09-08 13:25
I did from scratch again and it resolved the package issue..looks good...thanks....

**Comment by legra-ms** [comment] 2020-09-08 17:45
Reopening this issue based on additional feedback. https://github.com/Azure/Stormspotter/issues/18#issuecomment-688988914

The default behavior of Shiv to make the PYZ is supposed to prepend the folder in SHIV in the sys.path so that Python reads the PYZ packages before it reads the system-wide installation. For some reason, that doesn't appear to be happening. I will take a further look into what's happening there.

**Comment by legra-ms** [comment] 2020-09-08 18:02
This is interesting. When I check my sys.path that's modified by the PYZ file, it places the shiv path in the right spot as it comes before the system site-packages.

It was mentioned in another issue that a solution was found by providing the -S parameter to python, which prevents Python from importing the system-wide packages.

**Normal sys.path**
```
dcm@DESKTOP-212C8CQ:~/stormcollector$ SHIV_INTERPRETER=1 ./sscollector.pyz
Python 3.8.2 (default, Apr 27 2020, 15:53:34)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> import sys
>>> print(sys.path)
['./sscollector.pyz', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/home/dcm/.shiv/sscollector_f1bc86a4f6f6fe47e7a3adca48b68f91357a3dc18de4c8a256722b4a00ef2273/site-packages', '/home/dcm/.local/lib/python3.8/site-packages', '/usr/local/lib/python3.8/dist-packages', '/usr/lib/python3/dist-packages']
>>>
```

**Without site-packages loaded**
```
dcm@DESKTOP-212C8CQ:~/stormcollector$ SHIV_INTERPRETER=1 python3 -S ./sscollector.pyz
Python 3.8.2 (default, Apr 27 2020, 15:53:34)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> import sys
>>> print(sys.path)
['./sscollector.pyz', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/home/dcm/.shiv/sscollector_f1bc86a4f6f6fe47e7a3adca48b68f91357a3dc18de4c8a256722b4a00ef2273/site-packages']
```

Since the shiv folder comes first in the path, I am not sure why the site-packages are being loaded. But since all the packages are included, there's no reason to use the site-packages here. For the sake of a more immediate solution, I'm going to make `-S` the default behavior.

**Comment by legra-ms** [comment] 2020-09-08 19:39
I've updated the shebang line...could you grab this version and test it out? https://github.com/Azure/Stormspotter/actions/runs/245099797

If this works out, I may have to add a note for Windows users to explicitly run `python3 -IS sscollector.pyz` if they want to get the output of the tool in the same terminal.

**Comment by legra-ms** [comment] 2020-09-14 19:03
This issue is resolved by new beta release. https://github.com/Azure/Stormspotter/releases/tag/v1.0.0b1

**Closed by legra-ms** 2020-09-14 19:03 UTC
